### ISSUE TITLE
Where to find builds for rM 1?

### ISSUE THREAD

**Issue by JonathanTR** [ddvk/remarkable-update#2]
Hello, thanks for putting together this script. I've been trying to roll back my rM1 to some version of 2.5, since the last update borked remux. Given that the build mentioned in the readme is for rM2, I was wondering if you could point me towards where to find an appropriate build. Very much appreciate your time and help.

**Comment by ddvk** [comment]
doesnt the same url without 2 at the end work?

**Comment by JonathanTR** [comment]
Ha, I didn't even think of that. I guess I figured it would be hosted on different bucket, since this one's called /reMarkable-2.
