### ISSUE TITLE
2.14 update link

### ISSUE THREAD

**Issue by MininuxDev** [ddvk/remarkable-update#22]
Hi, i'm currently using a rm with software 2.12 toltec and ddvk-hacks. I want to update to at least 2.14 to get tags, however the tablet only wants to update to 2.15 (incompatible with toltec), so i need this tool to select the proper version. The problem is i can't find anywhere the links to get the right version, and changing the url doesn't work. How can we find the new updates download links ? 
thanks in advance

edit: welp 2 seconds after posting this issue (despite having searched the entire web before...) i found the filename for version 2.14.1.866 in issue #21 from which i deduced the url : [https://updates-download.cloud.remarkable.engineering/build/reMarkable%20Device%20Beta/RM110/2.14.1.866/2.14.1.866_reMarkable2-JLWa2mnXu1-.signed](https://updates-download.cloud.remarkable.engineering/build/reMarkable%20Device%20Beta/RM110/2.14.1.866/2.14.1.866_reMarkable2-JLWa2mnXu1-.signed)
It would still be useful to have instructions on how to find new versions

**Comment by laapsaap** [comment]
https://updates-download.cloud.remarkable.engineering:443/build/reMarkable%20Device%20Beta/RM110/2.15.1.1189/2.15.1.1189_reMarkable2-wVbHkgKisg-.signed

Your welcome.
I dont know how to find the old firmware urls, but if you run update-engine with the original update server, you can find the url in the journal log of update-engine.

**Comment by MininuxDev** [comment]
Oh I didn't think it would show up in the logs, thanks !
