### ISSUE TITLE
DNS issue 

### ISSUE THREAD

**Issue by Etn40ff** [ddvk/remarkable-update#3]
It is probably worth mentioning in the readme that, if the machine hosting the server has a name but this name is not resolved by the DNS server, the update will fail. This happens for example when trying the update via usb. A quick fix to this is to add the name to the remarkable's `/etc/hosts`.

**Comment by ddvk** [comment]
added to the readme

**Comment by Etn40ff** [comment]
For what is worth: I had set $SERVER to an IP address not a machine name but it still wanted to connect to $HOST; "if your dns sucks" might not be the issue here.

More precisely xochitl was able to contact the server and get the correct metadata. But then the binary download would not begin because it was supposed to happen through a connection at $HOSTNAME.

Anyway thank you for adding the clarification on the readme. People in need will figure it out I guess.

**Comment by ddvk** [comment]
what I meant is that with dnsmasq it works out of the box (in my case), and it depends on the router and the way the network is setup in general
