### ISSUE TITLE
update_engine won't start

### ISSUE THREAD

**Issue by zcy85611** [ddvk/remarkable-update#4]
I got a strange problem, my firmware version is 2.5.1.45, in the xochitl interface, the "check for updates" button is grey, I cannot even click on it, then I used ssh to login to the remarkable, tried "/usr/sbin/update_engine", it tells me "update_engine: error while loading shared libraries: libnghttp2.so.14: cannot open shared object file: No such file or directory", then I used entware to install the libnghttp2 1.38 - 1.43 to the "/usr/lib", all of them tells "update_engine: error while loading shared libraries: /usr/lib/libnghttp2.so.14: internal error", I've got no clue how to solve this problem, could you kindly help to look into it please? thank you

**Comment by ddvk** [comment]
it seems somethin got overwritten

**Comment by zcy85611** [comment]
Is there anyway to solve it? I don't even know if remarkable come with libnghttp2, mine remarkable don't have it, is it possible for you to share an update_engine and libnghttp2 file from your remarkable please?

**Comment by ddvk** [comment]
i neved had the full 2.5.1.4.5 update (it was never publicly avaiable), you can ask in the reddit or discord channels if someone has it
