### ISSUE TITLE
Bug: Error connecting server

### ISSUE THREAD

**Issue by nzbcorz** [ddvk/remarkable-update#5]
Here’s my config:
```
[General]
REMARKABLE_RELEASE_VERSION=2.5.1.45
SERVER=http://<ipaddress>:10001
```
Well there’re the error thrown while running `update_engine_client -check_for_update`

![BA3EEFEF-B9AE-4C85-8719-E0A46B04775C](https://user-images.githubusercontent.com/25114850/117854165-cd6c7e00-b2bb-11eb-9af9-66de84894fc9.png)

**Comment by ddvk** [comment]
make sure the update-engine is running first (it is not if you disabled the automatic updates) by doing: `systemctl start update-engine`

**Comment by nzbcorz** [comment]
My device version is 2.5.1.45 and here’s my config:

```
[General]
REMARKABLE_RELEASE_VERSION=2.5.1.45
SERVER=http://<ipaddress>:10001
```

Well I tried to start update-engine but this occurred:
![EEE819A1-00F9-490A-A3A1-190A006EEF70](https://user-images.githubusercontent.com/25114850/117997405-817e0f80-b375-11eb-9f50-27981e3f8e1f.png)

`systemctl restart`, `systemctl stop` or manually switch `Automatically updates` on device fails.
Still get the error above. Hummm I don’t know what to do next. Sorry for inconveniences.

**Comment by ddvk** [comment]
This is very bizarre, as if this version has a broken updater (you are the 2nd person with this problem). If you have access to a linux machine I could probably guide you and show you a different way to update your device, which needs the execution of some commands and python.

**Comment by ddvk** [comment]
i uploaded the 2.7 [update-engine](https://github.com/ddvk/remarkable-update/raw/update-engine/bin/update_engine)
you can try getting this on the device (`wget theurl`)  
then `chmod +x ./update-engine`  
`update-engine -f` and see if this one throws an error

**Comment by nzbcorz** [comment]
2.7’s update-engine doesn’t use `libnghttp2.so.16`, so it should be fine working. But I’m not sure if it’s compatible with `2.5.1.45`.

Sure I’ll test later. If you have another way to update you could tell please. I think I’ll handle that out.

**Comment by nzbcorz** [comment]
> This is very bizarre, as if this version has a broken updater (you are the 2nd person with this problem). If you have access to a linux machine I could probably guide you and show you a different way to update your device, which needs the execution of some commands and python.

Well I guess I need that method.
I tried via using 2.7’s `update-engine` but, lack of some libs (`libssl.so.1.1`, `libprotobuf.so.22.0.4`). So I managed to pull libs from my other device and created soft link. Then it still fails and `libnghttp2.so.14` is still needed. It’s quite weird since my 2.7’s device is able to run `system-update` just fine without that lib.

Please check logs below. Previous logs are about missing `libssl.so.1.1` and `libprotobuf.so.22.0.4`.
![586F0DCF-4062-4AFC-B408-A71474024A28](https://user-images.githubusercontent.com/25114850/118063487-c46ad200-b3cb-11eb-8771-6b473f6d2c5c.png)

Thanks for helping!

**Comment by nzbcorz** [comment]
So how exactly can I update system manually?

**Comment by ddvk** [comment]
get the latest version of the repo, go into the `extractor/` folder
use a virtual env or whatever and install the requirements: `pip install -r requirements.txt`  
extrat the image file you have with `extractor.py remarkable.signed` by default you'll have an `out` file
run the `push.sh out` script, which will write the rawimage to the alternative partition. reboot

**Comment by nzbcorz** [comment]
So where should I run this script on? On the device or in another env like Windows WSL?

Because on the WSL I got result like this (check the pic below)
```
ubuntu@DESKTOP-E076PCQ: /…/extractor$ sh push.sh out
root@10.11.99.1’s password:
push.sh : 7 : Bad substitution
 ```
![356831B1-EB40-446F-BF18-C9379251DA98](https://user-images.githubusercontent.com/25114850/118400675-2f026300-b695-11eb-8e89-1aee984e278f.png)

And as I checked the script a bit and found that it touches device’s partition and I’m afraid that it’ll do harm to the device while running straight LY on it.

So I’m quite wonder that where should run the script on. Thanks!

**Comment by ddvk** [comment]
you are right, it overwrites the alt parition with the whole image. you should run it on your host. 
also you should run it with  just `./push.sh` or bash as it useses bashisms

**Comment by nzbcorz** [comment]
As you see in the screenshot `./host.sh out` failed as well.

**Comment by ddvk** [comment]
make sure you can ping th host: `VM-4-3-UBUNTU`
