### ISSUE TITLE
update-engine failed ‘core-dump’

### ISSUE THREAD

**Issue by nzbcorz** [ddvk/remarkable-update#8]
Hi.

I hosted a server via `python serve.py`, and on device side `curl <IP>:8000` works.

So when I tried
```
systemctl restart update-engine
update_engine_client -check_for_update
```

And I got only one line response like "starting update" or whatchamacallit.

While it's still "up to date" on device's update UI.

So when I use journactl to observe I saw this:
![image](https://user-images.githubusercontent.com/25114850/122253957-3bc9df00-ceff-11eb-9e06-a3030ffe5185.png)

Since I'm now using a Win7 and unable to use WSL I can't use the method you mentioned before to wipe and force flash a firmware.

Any advice on what I should do, or is a normal ￼phenomenon? Thanks!

**Comment by nzbcorz** [comment]
Hi. Tonight I tested again and got same result.

When I didn't modified the server address, it showed that dbus driver is error somehow.

But when I try to modify the server address to mine, dbus error didn't show up. But error above occurred again.

Any idea about what's going on please?😂 Thanks so much.

**Comment by ddvk** [comment]
i forgot, did you try reverting to the other partition?
one more possibility is to extract the update, copy it to the home partitin

ssh to the tablet, and then do the dd from there by being careful with which partition is active, and the. switching and restarting

**Comment by nzbcorz** [comment]
I switched from `2.5` to `2.4`, then a toast told me to finish complete update showed up. See [pic](https://user-images.githubusercontent.com/25114850/122788834-50d0b480-d2e9-11eb-948f-cade72672266.jpeg).
Then after rebooting, it's still `2.4`.
However without changing the conf, it's now able to get update.
Then automatic update succeeds.
Thanks!

**Comment by nzbcorz** [comment]
He dear dev. It's been a while.

Here I met another device with the same problem... which is definitely annoyed.

It's a `reMarkable 1, version 0.0.481`.

I tried the old way which is to reverting partition, however it just went straight into factory mode, as perhaps the version is too old. ( see following pic)

![image](https://user-images.githubusercontent.com/25114850/140310445-75cd5346-8faa-469c-ae6c-c3b95b7ec61a.jpeg)

Thus I'm confused. I once met a device which is reMarkable 1, running on `1.8.11`. When I try to configure the update part, I first updated to `2.0.2.0`, then is the `2.10.2.356`. In a word it seems it has a step-installation when a old version is trying to update to the lastetest version.

So I'm worried that straightly manual flash the latest version will do harm to the device irreversibly.

Any suggestions on what to do next please? Thanks!

**Comment by ddvk** [comment]
well, this seems to be the factory partition with the qa stuff.
imho, putting the latest version should just work.

**Comment by nzbcorz** [comment]
Hum. Does that mean force flashing the latest version's firmware?
